version: '3.8'

services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  competances:
    build: ./competances
    ports:
      - "9000:9000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/competancesdb
    depends_on:
      - mongo

  brief:
    build: ./brief
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/briefdb
    depends_on:
      - mongo
      - competances

volumes:
  mongo_data: